source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SQLite-SwiftyJSON_Example', :exclusive => true do
  pod 'SQLite-SwiftyJSON', :path => '../'
end

target 'SQLite-SwiftyJSON_Tests', :exclusive => true do
  pod 'SQLite-SwiftyJSON', :path => '../'

  
end
