source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SQLite-SwiftyJSON_Example' do
  pod 'SQLite-SwiftyJSON', :path => '../'
end

target 'SQLite-SwiftyJSON_Tests' do
  pod 'SQLite-SwiftyJSON', :path => '../'
end
