platform :ios, '8.1'
use_frameworks!

target 'SQLite-SwiftyJSON_Example' do
  pod 'SQLiteSwiftyJSON', :path => '../'
end

target 'SQLite-SwiftyJSON_Tests' do
  pod 'SQLiteSwiftyJSON', :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
